# Generated by Django 5.1.2 on 2024-12-21 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algosee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candledata',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 21, 13, 58, 55, 8360), null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 21, 13, 58, 54, 998849), null=True),
        ),
        migrations.AlterField(
            model_name='marketfeed',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 21, 13, 58, 55, 8360), null=True),
        ),
        migrations.AlterField(
            model_name='optionexpiry',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 21, 13, 58, 55, 7361), null=True),
        ),
    ]
