# Generated by Django 5.1.2 on 2024-12-21 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algosee_app', '0002_alter_candledata_created_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakoutposition',
            name='set_order_side',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='candledata',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 21, 23, 22, 26, 549826), null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 21, 23, 22, 26, 536824), null=True),
        ),
        migrations.AlterField(
            model_name='marketfeed',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 21, 23, 22, 26, 551826), null=True),
        ),
        migrations.AlterField(
            model_name='optionexpiry',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 21, 23, 22, 26, 548827), null=True),
        ),
    ]
