# Generated by Django 5.1.2 on 2024-12-29 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algosee_app', '0003_breakoutposition_set_order_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakoutstrategy',
            name='trading_mode',
            field=models.CharField(blank=True, default='Paper', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='candledata',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 30, 0, 35, 17, 569993), null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 30, 0, 35, 17, 561994), null=True),
        ),
        migrations.AlterField(
            model_name='marketfeed',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 30, 0, 35, 17, 570993), null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='trading_mode',
            field=models.CharField(blank=True, default='Paper', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='optionexpiry',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 30, 0, 35, 17, 568993), null=True),
        ),
    ]
